### ISSUE TITLE
Generate random id_secret

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo-ci-action#18]
This should probably be an optional feature implemented in planemo and used in the action.
We use `id_secret` to encode integer primary keys, and these do change when running tests against a production server,
or when running tests in differently sized batches.

Sometimes (jbrowse for instance) these end up in the test data outputs, and will cause false positive test failures.
Similar idea for dates is implemented in https://github.com/galaxyproject/planemo-ci-action/pull/16

**Comment by bernt-matthias** [comment]
Seems that to some extend planemo already implements setting `id_secret` https://github.com/galaxyproject/planemo/blob/4225e10dfffb6b67f528d3c1ac31664c741089af/planemo/galaxy/config.py#L457 .. adding a cli parameter seems trivial. I just don't get if / how planemo sets this for the test instance. A `galaxy.yaml` seems not to be generated.
