### ISSUE TITLE
Passing env var to tested tool

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/planemo-ci-action#39]
Hi!
I've updated out github actions workflows this week on https://github.com/galaxy-genome-annotation/galaxy-tools/ and I'm having a problem [passing environment variables to a tested tool](https://github.com/galaxy-genome-annotation/galaxy-tools/pull/78/files#diff-1eb4e5fd5611777d4e597ef299a1cb5ba8050c28a2dabbd4fbc56205d69e5ddaR310)
Apparently, the ARROW_GLOBAL_CONFIG_PATH var I have defined is not seen by the command executed by the tool. Do you see a way I could make it work?

**Comment by mvdbeek** [comment]
That doesn't seem portable, i.e. you can't install the tool and have it work without setting up a special config. If it works locally it should work with the action, we don't do anything special there. Galaxy strips out environment variables for a clean environment, I would assume this also doesn't work locally ? I'd say the way to go is to set up a separate job config file with your environment variables ?

**Comment by abretaud** [comment]
These tools are exotic for sure :grimacing: 
It used to work some time ago, with an older galaxy version somehow

> I'd say the way to go is to set up a separate job config file with your environment variables ?

Would you have some example for that?
I'll also see if I can hack something to avoid using the env var (but not very confident on this)

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/13011 for the Galaxy change

**Comment by abretaud** [comment]
perfect thanks!
